apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
    app: fdb-kubernetes-operator-controller-manager
spec:
  selector:
    matchLabels:
      app: fdb-kubernetes-operator-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: fdb-kubernetes-operator-controller-manager
    spec:
      securityContext:
        runAsUser: 4059
        runAsGroup: 4059
        fsGroup: 4059
      volumes:
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: fdb-binaries
          emptyDir: {}
      serviceAccountName: fdb-kubernetes-operator-controller-manager
      initContainers:
        - name: foundationdb-kubernetes-init-7-3
          image: localhost:5001/tskimmett/fdb-sidecar-arm:7.3.56
          args:
            - "--copy-library"
            - "7.3"
            - "--copy-binary"
            - "fdbcli"
            - "--copy-binary"
            - "fdbbackup"
            - "--copy-binary"
            - "fdbrestore"
            - "--output-dir"
            - "/var/output-files/7.3.56"
            - "--init-mode"
          volumeMounts:
            - name: fdb-binaries
              mountPath: /var/output-files
      containers:
        - command:
            - /manager
          image: localhost:5001/tskimmett/fdb-kubernetes-operator:latest
          name: manager
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: metrics
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: logs
              mountPath: /var/log/fdb
            - name: fdb-binaries
              mountPath: /usr/bin/fdb
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
